### ISSUE TITLE
Getting a TimeoutError when creating reference

### ISSUE THREAD

**Issue by jigarius** [cilefen/backstop_ias#1]
I was running this command to test backstop:
    node backstop.js --command reference --suite iasedu-dynamic --url https://example.com/

Backstop runs for a while and then gives me this error:

```
SCENARIO > search grabar
x Close Browser
Puppeteer encountered an error while running scenario "ideas ajax math"
TimeoutError: waiting for selector "#edit-aff-2" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax math"
TimeoutError: waiting for selector "#edit-aff-2" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax math"
TimeoutError: waiting for selector "#edit-aff-2" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax math"
TimeoutError: waiting for selector "#edit-aff-2" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax featured"
TimeoutError: waiting for selector "#edit-aff-featured" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax featured"
TimeoutError: waiting for selector "#edit-aff-featured" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax featured"
TimeoutError: waiting for selector "#edit-aff-featured" failed: timeout 30000ms exceeded
Puppeteer encountered an error while running scenario "ideas ajax featured"
TimeoutError: waiting for selector "#edit-aff-featured" failed: timeout 30000ms exceeded

Run `$ backstop test` to generate diff report.
```

**Comment by cilefen** [comment]
Possibly the tested page is broken because an element with that ID never appears. I would delete that particular test in your fork and move on to test your own apps. 

Thanks for tryin this software!

**Comment by jigarius** [comment]
Thanks for the reply. I was thinking the same. I now realize that I have to prepare a `suite` and then run the tests with my own suite. The app looks promising. I'm closing this ticket as it is invalid.

**PS:** I wish it showed URLs on the report page.

**Comment by cilefen** [comment]
Oh you use https//www.ias.edu, which is the actual site it tests.

**Comment by cilefen** [comment]
...if you just want to try it out.

**Comment by cilefen** [comment]
It’s ok we have Varnish.

**Comment by jigarius** [comment]
Thanks for the suggestion. I think I'll explore it in more detail when I have a real use case. For now, I think it is pretty helpful and I will definitely give it a try.

**Comment by cilefen** [comment]
This is a wrapper for BackstopJS that lets you compare different sites, like dev and staging. Maybe I should generalize it for simpler reuse. Be my guest if you would like to do so. Maybe I will help.

**Comment by jigarius** [comment]
Ah! Now it makes more sense. I had the wrong repo. But anyway. It was still fun trying it out.

**Comment by cilefen** [comment]
Indeed. However this wrapper can handle some use cases that backstop can’t do on its own. For example, passing in a baseurl.
